name: CI/CD Test

on:
  push:
    branches: ["main"]

jobs:
  api_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install Newman
        run: npm install -g newman
      - name: Install dotnet project dependencies
        run: dotnet restore formbridge/formbridge.sln
      - name: Build
        run: dotnet build formbridge/formbridge.sln
      - name: Start Server
        run: cd formbridge/server && nohup dotnet run &
      - name: Run API-Tests
        run: newman run ./api-test/Test.postman_collection.json

  gui_tests:
    runs-on: ubuntu-latest
    needs: api_tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dotnet project dependencies
        run: dotnet restore formbridge/formbridge.sln
      - name: Build/Restore Playwright Project
        run: dotnet build End2EndTester/End2EndTester.csproj
      - name: Ensure browsers are installed
        run: cd End2EndTester && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      - name: Start server
        run: cd formbridge/server && nohup dotnet run &
      - name: Run GUI-tests
        run: dotnet test End2EndTester/End2EndTester.csproj

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: [api_tests, gui_tests]
    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /srv/www/<malmo/Mohsen # första gången
            cd /srv/www/malmo/Mohsen/formbridge # andra gången 
            git clone https://github.com/MarcelRx/TestTech.git # första gången
            git pull # andra gången
