name: CI/CD Test

on:
  push:
    branches: ["main"]

jobs:
  # API-tester job
  api_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install Newman
        run: npm install -g newman
      - name: Install dotnet project dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Start Server
        run: cd server && nohup dotnet run &
      - name: Run API-Tests
        run: newman run ./api-test/Test.postman_collection.json

  # GUI-tester job
  gui_tests:
    runs-on: ubuntu-latest
    needs: api_tests # Endast om API-testerna går igenom
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dotnet project dependencies
        run: dotnet restore
      - name: Build/Restore Playwright Project
        run: cd ShopTester.Tests && dotnet build
      - name: Ensure browsers are installed
        run: cd ShopTester.Tests && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      - name: Start server
        run: cd server && nohup dotnet run &
      - name: Run GUI-tests
        run: cd ShopTester.Tests && dotnet test

  # Deploy job
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: [api_tests, gui_tests] # Endast om testerna är godkända
    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}  # Din privata SSH-nyckel

      - name: Deploy App
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}        # T.ex. localhost eller din serveradress
          username: ${{ secrets.USERNAME }} # T.ex. ditt användarnamn på servern
          key: ${{ secrets.SSH_KEY }}      # Din SSH-nyckel
          port: ${{ secrets.PORT }}        # Om du använder standard SSH-port (22), annars din serverport
          script: |
            # Sätt upp miljövariabler för databasanslutning
            export DB_HOST=${{ secrets.HOST }}
            export DB_PORT=${{ secrets.PORT }}
            export DB_USERNAME=${{ secrets.USERNAME }}
            export DB_PASSWORD=${{ secrets.PASSWORD }}
            export DB_DATABASE=${{ secrets.DATABASE }}
            
            # Stäng av och starta om servern med de senaste ändringarna
            source /root/.nvm/nvm.sh
            nvm use v20.12.2
            cd /srv/www/formbridge
            git pull
            cd client
            npm ci
            npm run build
            cd ../server
            dotnet restore
            pm2 stop formbridge
            pm2 delete formbridge
            pm2 start "dotnet run" --name formbridge
